//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities.DataTableExt.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities.DataTableExt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество затронутых строк.
        /// </summary>
        internal static string AffectedRowsCount_Description {
            get {
                return ResourceManager.GetString("AffectedRowsCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AffectedRowsCount.
        /// </summary>
        internal static string AffectedRowsCount_ScreenName {
            get {
                return ResourceManager.GetString("AffectedRowsCount_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Criteria_Description {
            get {
                return ResourceManager.GetString("Criteria_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критерии поиска.
        /// </summary>
        internal static string Criteria_ScreenName {
            get {
                return ResourceManager.GetString("Criteria_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string InputTable_Description {
            get {
                return ResourceManager.GetString("InputTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DataTable.
        /// </summary>
        internal static string InputTable_ScreenName {
            get {
                return ResourceManager.GetString("InputTable_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условие объединения.
        /// </summary>
        internal static string JoinCondition_Description {
            get {
                return ResourceManager.GetString("JoinCondition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JoinCondition.
        /// </summary>
        internal static string JoinCondition_ScreenName {
            get {
                return ResourceManager.GetString("JoinCondition_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип объединения (Inner, Left, Right, Full).
        /// </summary>
        internal static string JoinType_Description {
            get {
                return ResourceManager.GetString("JoinType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JoinType.
        /// </summary>
        internal static string JoinType_ScreenName {
            get {
                return ResourceManager.GetString("JoinType_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string OutTable_Description {
            get {
                return ResourceManager.GetString("OutTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DataTable.
        /// </summary>
        internal static string OutTable_ScreenName {
            get {
                return ResourceManager.GetString("OutTable_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL подобный запрос, пример &apos;Column1 &gt; 30&apos;.
        /// </summary>
        internal static string Query_Description {
            get {
                return ResourceManager.GetString("Query_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Query.
        /// </summary>
        internal static string Query_ScreenName {
            get {
                return ResourceManager.GetString("Query_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результирующая таблица.
        /// </summary>
        internal static string ResultTable_Description {
            get {
                return ResourceManager.GetString("ResultTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ResultTable.
        /// </summary>
        internal static string ResultTable_ScreenName {
            get {
                return ResourceManager.GetString("ResultTable_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Искать до первого совпадения.
        /// </summary>
        internal static string SearchFirst_Description {
            get {
                return ResourceManager.GetString("SearchFirst_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До первого.
        /// </summary>
        internal static string SearchFirst_ScreenName {
            get {
                return ResourceManager.GetString("SearchFirst_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string SearchResults_Description {
            get {
                return ResourceManager.GetString("SearchResults_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат.
        /// </summary>
        internal static string SearchResults_ScreenName {
            get {
                return ResourceManager.GetString("SearchResults_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входная таблица.
        /// </summary>
        internal static string SourceTable_Description {
            get {
                return ResourceManager.GetString("SourceTable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DataTable.
        /// </summary>
        internal static string SourceTable_ScreenName {
            get {
                return ResourceManager.GetString("SourceTable_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL-подобный запрос.
        /// </summary>
        internal static string SqlQuery_Description {
            get {
                return ResourceManager.GetString("SqlQuery_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SqlQuery.
        /// </summary>
        internal static string SqlQuery_ScreenName {
            get {
                return ResourceManager.GetString("SqlQuery_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входная таблица 1.
        /// </summary>
        internal static string Table1_Description {
            get {
                return ResourceManager.GetString("Table1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table1.
        /// </summary>
        internal static string Table1_ScreenName {
            get {
                return ResourceManager.GetString("Table1_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входная таблица 2.
        /// </summary>
        internal static string Table2_Description {
            get {
                return ResourceManager.GetString("Table2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table2.
        /// </summary>
        internal static string Table2_ScreenName {
            get {
                return ResourceManager.GetString("Table2_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TableFilter.
        /// </summary>
        internal static string TableFilter_ScreenName {
            get {
                return ResourceManager.GetString("TableFilter_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск данных.
        /// </summary>
        internal static string TableSearch_ScreenName {
            get {
                return ResourceManager.GetString("TableSearch_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить произвольный SQL-подобный запрос над таблицей.
        /// </summary>
        internal static string TableSqlQuery_ScreenName {
            get {
                return ResourceManager.GetString("TableSqlQuery_ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string UseRegex_Description {
            get {
                return ResourceManager.GetString("UseRegex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используем Regex.
        /// </summary>
        internal static string UseRegex_ScreenName {
            get {
                return ResourceManager.GetString("UseRegex_ScreenName", resourceCulture);
            }
        }
    }
}
